task:
  name: Crazyflie
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 2.5
    maxEpisodeLength: 700
    enableDebugVis: false
    clipObservations: 5.0
    clipActions: 1.0
  sim:
    dt: 0.01
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    add_ground_plane: true
    add_distant_light: true
    use_flatcache: true
    enable_scene_query_support: false
    enable_cameras: false
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 6
      solver_velocity_iteration_count: 0
      contact_offset: 0.02
      rest_offset: 0.001
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      friction_offset_threshold: 0.04
      friction_correlation_distance: 0.025
      enable_sleeping: true
      enable_stabilization: false
      gpu_max_rigid_contact_count: 524288
      gpu_max_rigid_patch_count: 81920
      gpu_found_lost_pairs_capacity: 4194304
      gpu_found_lost_aggregate_pairs_capacity: 33554432
      gpu_total_aggregate_pairs_capacity: 4194304
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 67108864
      gpu_temp_buffer_capacity: 16777216
      gpu_max_num_partitions: 8
    crazyflie:
      override_usd_defaults: false
      fixed_base: false
      enable_self_collisions: true
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 6
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 1000.0
    ball:
      override_usd_defaults: false
      fixed_base: true
      enable_self_collisions: false
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 6
      solver_velocity_iteration_count: 0
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 1000.0
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 256
        - 128
        activation: tanh
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:Crazyflie,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      device: ${....rl_device}
      device_name: ${....rl_device}
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.01
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0001
      lr_schedule: adaptive
      kl_threshold: 0.016
      score_to_win: 100000
      max_epochs: ${resolve_default:1000,${....max_iterations}}
      save_best_after: 50
      save_frequency: 50
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 16384
      mini_epochs: 8
      critic_coef: 2
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
task_name: ${task.name}
experiment: ''
num_envs: 10
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gspu
sim_device: gpu
device_id: 0
rl_device: cuda:0
num_threads: 4
solver_type: 1
test: true
checkpoint: /home/student/PycharmProjects/pythonProject1/omniisaacgymenvs/runs/Crazyflie/nn/Crazyflie.pth
headless: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: omniisaacgymenvs
